site_name: Análise de Qualidade Mepa Energia

repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T02_CAROL-SHAW
repo_name: 2025.2-carolShaw
site_description: "Documentação da Análise de Qualidade Mepa Energia"

nav:
  - Home: index.md
  

  - Fase 1:
    - Proposito de Avaliação: pages/Modulo1/propositoDeAvaliacao.md
    - Participação Fase 1: pages/Modulo1/partIntegrantesFase1.md

  - Fase 2:
    - Planejamento de Avaliação: pages/Modulo2/planejamentoDaAvaliacao.md
    - Participação Fase 2: pages/Modulo2/partIntegrantesFase2.md

  - Fase 3:
    - Descrição da Medição: pages/Modulo3/descricaoDaMedicao.md
    - Participação Fase 3: pages/Modulo3/partIntegrantesFase3.md

  - Fase 4:
    - Execução da Medição: pages/Modulo4/execucaoDaMedicao.md
    - Participação Fase 4: pages/Modulo4/partIntegrantesFase4.md

  - Atas:
    - Ata 1 - Fase 1: pages/atas/ata1.md
    - Ata 2 - Fase 3: pages/atas/ata2.md

theme:
  name: material
  language: pt-BR

  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking
  
  palette:
    - scheme: default
      primary: '--md-primary-fg-color'
      accent: '--md-primary-fg-color'
      toggle:
        icon: material/lightbulb-outline
        name: Mude para o tema escuro
        
    - scheme: slate
      primary: '--md-primary-fg-color'
      accent: '--md-primary-fg-color'
      toggle:
        icon: material/lightbulb
        name: Mude para o tema claro

  
  logo: assets/shawR2I.ico
  favicon: assets/shawR2.png
  highlightjs: true

extra_css:
  - overrides/styles.css

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
